/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TheVolts
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EncabezadoNomina extends javax.swing.JPanel {

 DefaultTableModel tabla = new DefaultTableModel(){
       
        public boolean isCellEditable(int Fila, int Colum) {
            return false;
        }
    };
    
    public void cargarTitulosColumas(){
        tabla.addColumn("CODIGO_NOMINA");
        tabla.addColumn("FECHA_INICIAL_NOMINA");
        tabla.addColumn("FECHA_FINAL_NOMINA");
        tabla.addColumn("VALOR_NOMINA");
        this.Tbl_Nomina.setModel(tabla);
    }
    
    private void Clear(){
        while (tabla.getRowCount() > 0) {
               tabla.removeRow(0);
        }
    }
    
    
    public EncabezadoNomina() {
        initComponents();
        cargarTitulosColumas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCodigoNomina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Nomina = new javax.swing.JTable();
        BtnBusqueda = new javax.swing.JButton();

        jLabel1.setText("Código Nomina");

        Tbl_Nomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tbl_Nomina);

        BtnBusqueda.setText("Buscar");
        BtnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TxtCodigoNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCodigoNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBusqueda))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBusquedaActionPerformed
        Clear();
        String datos[] = new String[4];
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from encabezado_nomina where codigo_nomina = ?");
            pst.setString(1, TxtCodigoNomina.getText().trim());

            ResultSet ConsultaNomina = pst.executeQuery();

            if(ConsultaNomina.next()){
                Object[] fila = new Object[5];
                fila[0] = ConsultaNomina.getString("codigo_nomina");
                fila[1] = ConsultaNomina.getString("FechaInicial_Nomina");
                fila[2] = ConsultaNomina.getString("FechaFinal_Nomina");
                fila[3] = ConsultaNomina.getString("Valor_Nomina");
                tabla.addRow(fila);
            }else{
                JOptionPane.showMessageDialog(null, "No Se Encuentra La Nomina");
            }
            this.Tbl_Nomina.setModel(tabla);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "No Se Encuentra La Nomina");
        }
    }//GEN-LAST:event_BtnBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBusqueda;
    private javax.swing.JTable Tbl_Nomina;
    private javax.swing.JTextField TxtCodigoNomina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
