/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TheVolts
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class Ingresp_empleado extends javax.swing.JFrame {

    /**
     * Creates new form Ingresp_empleado
     */
    public Ingresp_empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btn_Ingreso_Login = new javax.swing.JButton();
        txtsalario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigo_puesto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        combopuesto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combodept = new javax.swing.JComboBox<>();
        txtnombre_puesto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtnombre_puesto1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtsalariobusqueda = new javax.swing.JTextField();
        btn_Busqueda_Login = new javax.swing.JButton();
        btn_Busqueda_Login2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo_puesto1 = new javax.swing.JTextField();
        txtModificar = new javax.swing.JButton();
        txtLimpiar = new javax.swing.JButton();
        combobusquedadept = new javax.swing.JComboBox<>();
        combobusqpuesto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Salario");

        btn_Ingreso_Login.setText("Ingresar Empleado");
        btn_Ingreso_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingreso_LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Puesto");

        jLabel6.setText("Codigo Puesto");

        jLabel7.setText("Codigo Dept");

        combopuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------", "Gerente", "Supervisor", "Contador", "Reclutador", "Programador", "Tecnico", "Planificador" }));

        jLabel3.setText("Nombre Empleado");

        combodept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------", "Proyectos", "Informatica", "Capacitacion y Desarrollo", "Reclutamiento y Seleccion", "Nominas" }));

        jLabel4.setText("Nombre Empleado");

        jLabel8.setText("Salario");

        jLabel9.setText("Codigo Puesto");

        jLabel10.setText("Codigo Dept");

        btn_Busqueda_Login.setText("Buscar");
        btn_Busqueda_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Busqueda_LoginActionPerformed(evt);
            }
        });

        btn_Busqueda_Login2.setText("Eliminar");
        btn_Busqueda_Login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Busqueda_Login2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Puesto");

        txtModificar.setText("Actualizar");
        txtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarActionPerformed(evt);
            }
        });

        txtLimpiar.setText("Limpiar");
        txtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimpiarActionPerformed(evt);
            }
        });

        combobusquedadept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------", "Proyectos", "Informatica", "Capacitacion y Desarrollo", "Reclutamiento y Seleccion", "Nominas" }));

        combobusqpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------", "Gerente", "Supervisor", "Contador", "Reclutador", "Programador", "Tecnico", "Planificador" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtsalariobusqueda, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre_puesto1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobusquedadept, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combobusqpuesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Busqueda_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btn_Busqueda_Login2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(65, 65, 65)
                        .addComponent(txtcodigo_puesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodigo_puesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Busqueda_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Busqueda_Login2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnombre_puesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsalariobusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobusqpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(combobusquedadept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(53, 398, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combodept, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcodigo_puesto)
                                .addComponent(txtnombre_puesto)
                                .addComponent(txtsalario)
                                .addComponent(combopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btn_Ingreso_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnombre_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combopuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combodept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Ingreso_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Ingreso_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingreso_LoginActionPerformed

        String caso_puesto,cod_puesto="";
        caso_puesto=String.valueOf(combopuesto.getSelectedItem());

        String caso_dept,cod_dept="";
        caso_dept=String.valueOf(combodept.getSelectedItem());
        //if para que seleccione en los combos algo diferente de ---------
        if (caso_puesto=="----------------" || caso_dept=="----------------"){
            //mensaje de error
            JOptionPane.showMessageDialog(null,"No ha Completado Todos los Datos");
        }else{
            //conexion a la BD
            try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
                PreparedStatement pst = cn.prepareStatement("insert into empleado values(?,?,?,?,?)");

                switch(caso_puesto){
                    case "Gerente":{cod_puesto="P1";}break;
                    case "Supervisor":{cod_puesto="P2";}break;
                    case "Contador":{cod_puesto="P3";}break;
                    case "Reclutador":{cod_puesto="P4";}break;
                    case "Programador":{cod_puesto="P5";}break;
                    case "Tecnico":{cod_puesto="P6";}break;
                    case "Planificador":{cod_puesto="P7";}break;

                }

                switch(caso_dept){
                    case "Proyectos":{cod_dept="D1";}break;
                    case "Informatica":{cod_dept="D2";}break;
                    case "Capacitacion y Desarrollo":{cod_dept="D3";}break;
                    case "Reclutamiento y Seleccion":{cod_dept="D4";}break;
                    case "Nominas":{cod_dept="D5";}break;

                }

                pst.setString(1, txtcodigo_puesto.getText().trim());
                pst.setString(2, txtnombre_puesto.getText().trim());
                pst.setString(3, txtsalario.getText().trim());
                pst.setString(4,cod_puesto);
                pst.setString(5 ,cod_dept);

                pst.executeUpdate();
                txtcodigo_puesto.setText("");
                txtnombre_puesto.setText("");
                txtsalario.setText("");

                JOptionPane.showMessageDialog(null,"Registro Exitoso");
            }catch (Exception e){

                JOptionPane.showMessageDialog(null,"Error al acceder a la Base de Datos");
            }

        }//fin if
    }//GEN-LAST:event_btn_Ingreso_LoginActionPerformed

    private void btn_Busqueda_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Busqueda_LoginActionPerformed

        
        String puesto,depto,showpuesto="",showdepto="";

        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from empleado where codigo_empleado = ?");
            pst.setString(1, txtcodigo_puesto1.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                txtnombre_puesto1.setText(rs.getString("nombre_empleado"));
                txtsalariobusqueda.setText(rs.getString("sueldo_empleado"));

                puesto=rs.getString("codigo_puesto");
                depto=rs.getString("codigo_departamento");

                switch(puesto){
                    case "P1":{showpuesto="Gerente";}break;
                    case "P2":{showpuesto="Supervisor";}break;
                    case "P3":{showpuesto="Contador";}break;
                    case "P4":{showpuesto="Reclutador";}break;
                    case "P5":{showpuesto="Programador";}break;
                    case "P6":{showpuesto="Tecnico";}break;
                    case "P7":{showpuesto="Planificador";}break;

                }//fin switch puesto

                switch(depto){
                    case "D1":{showdepto="Proyectos";}break;
                    case "D2":{showdepto="Informatica";}break;
                    case "D3":{showdepto="Capacitacion  y Desarrollo";}break;
                    case "D4":{showdepto="Reclutamiento y Seleccion";}break;
                    case "D5":{showdepto="Nominas";}break;

                }//fin switch depto

                combobusqpuesto.setSelectedItem(showpuesto);
                combobusquedadept.setSelectedItem(showdepto);

            } else {
                JOptionPane.showMessageDialog(null, "Empleador no Encontrado");
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se ha podido Realizar la Busqueda");

        }

    }//GEN-LAST:event_btn_Busqueda_LoginActionPerformed

    private void txtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimpiarActionPerformed

        txtcodigo_puesto.setText("");
        txtnombre_puesto.setText("");
        txtsalario.setText("");
        txtcodigo_puesto1.setText("");
        txtnombre_puesto1.setText("");
        txtsalariobusqueda.setText("");
        

        // TODO add your handling code here:
    }//GEN-LAST:event_txtLimpiarActionPerformed

    private void btn_Busqueda_Login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Busqueda_Login2ActionPerformed

        
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from empleado where codigo_empleado = ?");

            pst.setString(1, txtcodigo_puesto1.getText().trim());
            pst.executeUpdate();

            txtcodigo_puesto.setText("");
            txtnombre_puesto.setText("");
            txtsalario.setText("");
            txtcodigo_puesto1.setText("");
            txtnombre_puesto1.setText("");
            txtsalariobusqueda.setText("");
            

            JOptionPane.showMessageDialog(null, "Puesto Eliminado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido Eliminar");
        }

    }//GEN-LAST:event_btn_Busqueda_Login2ActionPerformed

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed

        String puesto,depto,showpuesto="",showdepto="";
           //Codigo que permite actualizar registros en la base de datos
        try {
                    
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/umg", "root", "");
            PreparedStatement pst = cn.prepareStatement("update empleado set nombre_empleado = ?, sueldo_empleado = ?, codigo_puesto = ?, codigo_departamento = ? where codigo_empleado = " + txtcodigo_puesto1);
            
            pst.setString(1, txtnombre_puesto1.getText().trim());
            pst.setString(2, txtsalariobusqueda.getText().trim());
          
            puesto=String.valueOf(combobusqpuesto.getSelectedItem());
            depto=String.valueOf(combobusquedadept.getSelectedItem());

               switch(puesto){
                    case "Gerente":{showpuesto="P1";}break; 
                    case "Supervisor":{showpuesto="P2";}break;
                    case "Contador":{showpuesto="P3";}break;
                    case "Reclutador":{showpuesto="P4";}break;
                    case "Programador":{showpuesto="P5";}break;
                    case "Tecnico":{showpuesto="P6";}break;
                    case "Planificador":{showpuesto="P7";}break;

                }

                switch(depto){
                    case "Proyectos":{showdepto="D1";}break;
                    case "Informatica":{showdepto="D2";}break;
                    case "Capacitacion y Desarrollo":{showdepto="D3";}break;
                    case "Reclutamiento y Seleccion":{showdepto="D4";}break;
                    case "Nominas":{showdepto="D5";}break;

                }//switch depto

                
            
            pst.setString(3, showpuesto.trim());
            pst.setString(4, showdepto.trim());      
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Modificacion Exitosa");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido Modificar los Datos del Empleado");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresp_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresp_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresp_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresp_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresp_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Busqueda_Login;
    private javax.swing.JButton btn_Busqueda_Login2;
    private javax.swing.JButton btn_Ingreso_Login;
    private javax.swing.JComboBox<String> combobusqpuesto;
    private javax.swing.JComboBox<String> combobusquedadept;
    private javax.swing.JComboBox<String> combodept;
    private javax.swing.JComboBox<String> combopuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtLimpiar;
    private javax.swing.JButton txtModificar;
    private javax.swing.JTextField txtcodigo_puesto;
    private javax.swing.JTextField txtcodigo_puesto1;
    private javax.swing.JTextField txtnombre_puesto;
    private javax.swing.JTextField txtnombre_puesto1;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JTextField txtsalariobusqueda;
    // End of variables declaration//GEN-END:variables
}
